name: CI
on:
  push:
    branches: [ develop, master ]
jobs:
  build:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Create env file
        run: |
          touch .env
          echo HOST=${{ secrets.ENV_NODE_ENV }} >> .env
          echo HOST=${{ secrets.ENV_HOST }} >> .env
          echo PORT=${{ secrets.ENV_PORT }} >> .env
          echo MONGO_PORT=${{ secrets.ENV_MONGO_PORT }} >> .env
      - name: Create private.key file
        run: |
          touch private.key
          echo HOST=${{ secrets.PRIVATE_KEY }} >> private.key
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '6.0'
      - name: Test
        run: npm test
      - name: Sonar
        if: success()
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}