name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '17.x'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Sonar
        if: success()
        run: >
          mvn -B verify -DskipTests sonar:sonar
          -Dsonar.projectKey=JorgeDSDP_intellideck
          -Dsonar.organization=jorge88
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}